version: '3'
services:
  api:
    build: .
    ports:
      - "10000:3000" # Match this with Render’s expected port
    environment:
      - NODE_ENV=production
      - PORT=3000 # Ensure Render can dynamically set this
